### ISSUE TITLE
被签名的交易太大，sensilet crash 或无响应

### ISSUE THREAD

**Issue by zhfnjust** [brimless-lab/sensilet#5]
部分内存较小的电脑会直接 crash， 比如 我的mac mini 8G内存

部分内存较大的电脑出现无响应卡顿，等很久才出现签名确认按钮：

调用函数：

```js
    let res = await this.sensilet.signTx({
      list:[
        {
          txHex: rawtx,
          address: getAddressFromP2PKH(script, this.network),
          scriptHex: script,
          inputIndex: inputIndex,
          satoshis: satoshis,
          sigtype: sigHashType
        }
      ]
    });
```

[txHex.zip](https://github.com/brimless-lab/sensilet/files/9399693/txHex.zip)

address: `mt8YEKUv4AG8FgoqwdFPC715TCK4FV97rX`
script: `76a9148a5c65661e0b25167c6cbd7263eb37225237aaef88ac`
inputIndex: `0`
satoshis: `83775`
sigHashType: `65`

**Comment by huanniangstudio** [comment]
交易太大了，交易分析时处理时间太长。现在改为对2MB以上的交易只做最简单的解码分析，不分析其中的sensible的内容。5fe19973b265c3a845bd415356ebbe51c186f61e
