### ISSUE TITLE
被签名的交易太大，无法发送给 sensilet

### ISSUE THREAD

**Issue by zhfnjust** [brimless-lab/sensilet#6]
被签名的交易太大, 无法发送给 sensilet

![image](https://user-images.githubusercontent.com/995909/186348384-07b99e70-1aee-4a4f-8c44-45c88eca1656.png)

[txHex.zip](https://github.com/brimless-lab/sensilet/files/9413509/txHex.zip)

address: `mt8YEKUv4AG8FgoqwdFPC715TCK4FV97rX`
script: `76a9148a5c65661e0b25167c6cbd7263eb37225237aaef88ac`
inputIndex: `1`
satoshis: `996806`
sigHashType: `65`

**Comment by slient-coder** [comment]
浏览器限制，无法解决
